Reduce the use of variable rc

diff --git a/usr/bin/kz-build b/usr/bin/kz-build
--- a/usr/bin/kz-build
+++ b/usr/bin/kz-build
@@ -76,6 +76,8 @@ readonly -A DEB_TARGETS=(
 # Variables
 ###############################################################################
 
+declare error_flag=false
+
 
 ###############################################################################
 # Functions
@@ -83,7 +85,6 @@ readonly -A DEB_TARGETS=(
 
 # This function handles the script options and arguments.
 function check_input {
-    local -i rc=0
     local parsed=''
 
     parsed=$(
@@ -92,11 +93,7 @@ function check_input {
                 --longoptions   "$OPTIONS_LONG"     \
                 --name          "$DISPLAY_NAME"     \
                 --              "$@"
-        ) || rc=$?
-    if [[ $rc -ne $OK ]]; then
-        printf '%s\n' "$USAGE_LINE"
-        exit $ERROR
-    fi
+        ) || ( printf '%s\n' "$USAGE_LINE"; exit $ERROR )
     eval set -- "$parsed"
 
     process_common_options "$@"
@@ -168,16 +165,9 @@ function check_repos {
 
 # This function check the scripts.
 function check_scripts {
-    local -i rc=0
-
     msg_info "$(gettext 'Check scripts (kz check)...')"
     # Call kz-check.
-    "$SCRIPTS_REPO"/usr/bin/kz check || rc=$?
-    if [[ $rc -ne $OK ]]; then
-        msg_error "
-$(gettext 'Fix all the messages above.')"
-        exit $rc
-    fi
+    "$SCRIPTS_REPO"/usr/bin/kz check || error_flag=true
 }
 
 
@@ -348,37 +338,29 @@ function install_package {
 
 # This function performs an installation verification procedure (IVP).
 function run_ivp {
-    local -i rc=0
-
     msg_info "$(gettext 'Run IVP (kz ivp)...')"
     # Call kz-ivp.
-    kz ivp || rc=$?
-    if [[ $rc -ne $OK ]]; then
-        msg_error "
-$(gettext 'Fix all the messages above.')"
-        exit $rc
-    fi
+    kz ivp || error_flag=true
 }
 
 
 # This function checks the website for missing or not used files.
 function check_website {
-    local -i rc=0
-
     msg_info "$(gettext 'Check website (rchecklink)...')"
     # Call rchecklink.
-    rchecklink || rc=$?
-    if [[ $rc -ne $OK ]]; then
-        msg_error "
-$(gettext 'Fix all the messages above.')"
-        exit $rc
-    fi
+    rchecklink || error_flag=true
 }
 
 
 # This function controls the termination of the script.
 function term_script {
-    exit $OK
+    if $error_flag; then
+        msg_error "
+$(gettext 'Fix all the messages above.')"
+        exit $ERROR
+    else
+        exit $OK
+    fi
 }
 
 
diff --git a/usr/bin/kz-check b/usr/bin/kz-check
--- a/usr/bin/kz-check
+++ b/usr/bin/kz-check
@@ -53,7 +53,6 @@ declare error_flag=false
 
 # This function handles the script options and arguments.
 function check_input {
-    local -i rc=0
     local parsed=''
 
     parsed=$(
@@ -62,11 +61,7 @@ function check_input {
                 --longoptions   "$OPTIONS_LONG"     \
                 --name          "$DISPLAY_NAME"     \
                 --              "$@"
-        ) || rc=$?
-    if [[ $rc -ne $OK ]]; then
-        printf '%s\n' "$USAGE_LINE"
-        exit $ERROR
-    fi
+        ) || ( printf '%s\n' "$USAGE_LINE"; exit $ERROR )
     eval set -- "$parsed"
 
     process_common_options "$@"
diff --git a/usr/bin/kz-deploy b/usr/bin/kz-deploy
--- a/usr/bin/kz-deploy
+++ b/usr/bin/kz-deploy
@@ -56,7 +56,6 @@ readonly UPLOADS_REPO_DISTDIR=$UPLOADS_REPO/dist
 
 # This function handles the script options and arguments.
 function check_input {
-    local -i rc=0
     local parsed=''
 
     parsed=$(
@@ -65,11 +64,7 @@ function check_input {
                 --longoptions   "$OPTIONS_LONG"     \
                 --name          "$DISPLAY_NAME"     \
                 --              "$@"
-        ) || rc=$?
-    if [[ $rc -ne $OK ]]; then
-        printf '%s\n' "$USAGE_LINE"
-        exit $ERROR
-    fi
+        ) || ( printf '%s\n' "$USAGE_LINE"; exit $ERROR )
     eval set -- "$parsed"
 
     process_common_options "$@"
@@ -146,15 +141,10 @@ function check_repos {
 
 # This function builds package kz.
 function build_package {
-    local -i rc=0
-
     msg_info "$(gettext 'Build package and website (kz build)...')
 "
     # Call kz-build.
-    "$SCRIPTS_REPO"/usr/bin/kz build || rc=$?
-    if [[ $rc -ne $OK ]]; then
-        exit $rc
-    fi
+    "$SCRIPTS_REPO"/usr/bin/kz build || exit $ERROR
 }
 
 
diff --git a/usr/bin/kz-getdeb b/usr/bin/kz-getdeb
--- a/usr/bin/kz-getdeb
+++ b/usr/bin/kz-getdeb
@@ -57,7 +57,6 @@ readonly HELP
 function check_input {
     local files_found
     files_found=$(ls -C kz.{1..99} 2> /dev/null || true)
-    local -i rc=0
     local parsed=''
 
     # If the kz.{1..99} files exist, possible after multiple wget's, clean them
@@ -75,11 +74,7 @@ function check_input {
                 --longoptions   "$OPTIONS_LONG"     \
                 --name          "$DISPLAY_NAME"     \
                 --              "$@"
-        ) || rc=$?
-    if [[ $rc -ne $OK ]]; then
-        printf '%s\n' "$USAGE_LINE"
-        exit $ERROR
-    fi
+        ) || ( printf '%s\n' "$USAGE_LINE"; exit $ERROR )
     eval set -- "$parsed"
 
     # If source kz_common.sh has failed, e.g. in wget kz and bash kz sequence.
diff --git a/usr/bin/kz-getdev b/usr/bin/kz-getdev
--- a/usr/bin/kz-getdev
+++ b/usr/bin/kz-getdev
@@ -51,7 +51,6 @@ readonly HELP
 
 # This function handles the script options and arguments.
 function check_input {
-    local -i rc=0
     local parsed=''
 
     parsed=$(
@@ -60,11 +59,7 @@ function check_input {
                 --longoptions   "$OPTIONS_LONG"     \
                 --name          "$DISPLAY_NAME"     \
                 --              "$@"
-        ) || rc=$?
-    if [[ $rc -ne $OK ]]; then
-        printf '%s\n' "$USAGE_LINE"
-        exit $ERROR
-    fi
+        ) || ( printf '%s\n' "$USAGE_LINE"; exit $ERROR )
     eval set -- "$parsed"
 
     process_common_options "$@"
diff --git a/usr/bin/kz-gset b/usr/bin/kz-gset
--- a/usr/bin/kz-gset
+++ b/usr/bin/kz-gset
@@ -87,7 +87,6 @@ declare option_resetfavs=false
 
 # This function handles the script options and arguments.
 function check_input {
-    local -i rc=0
     local parsed=''
 
     parsed=$(
@@ -96,11 +95,7 @@ function check_input {
                 --longoptions   "$OPTIONS_LONG$X_OPTIONS_LONG"      \
                 --name          "$DISPLAY_NAME"                     \
                 --              "$@"
-        ) || rc=$?
-    if [[ $rc -ne $OK ]]; then
-        printf '%s\n' "$USAGE_LINE"
-        exit $ERROR
-    fi
+        ) || ( printf '%s\n' "$USAGE_LINE"; exit $ERROR )
     eval set -- "$parsed"
 
     process_common_options "$@"
diff --git a/usr/bin/kz-menu b/usr/bin/kz-menu
--- a/usr/bin/kz-menu
+++ b/usr/bin/kz-menu
@@ -103,7 +103,6 @@ declare option_gui=false
 
 # This function handles the script options and arguments.
 function check_input {
-    local -i rc=0
     local parsed=''
 
     parsed=$(
@@ -112,11 +111,7 @@ function check_input {
                 --longoptions   "$OPTIONS_LONG$X_OPTIONS_LONG"      \
                 --name          "$DISPLAY_NAME"                     \
                 --              "$@"
-        ) || rc=$?
-    if [[ $rc -ne $OK ]]; then
-        printf '%s\n' "$USAGE_LINE"
-        exit $ERROR
-    fi
+        ) || ( printf '%s\n' "$USAGE_LINE"; exit $ERROR )
     eval set -- "$parsed"
 
     process_common_options "$@"
@@ -163,8 +158,6 @@ function process_input {
 
 # This function shows and processes menu #1 in GUI mode.
 function process_menu1_gui {
-    local -i rc=0
-
     while true; do
         title=$MENU1_TITLE
         REPLY=$(
@@ -186,10 +179,7 @@ function process_menu1_gui {
                     FALSE 4 "${MENU1_ACTIONS[4]}" "${MENU1_COMMANDS[4]}"    \
                     FALSE 5 "${MENU1_ACTIONS[5]}" "${MENU1_COMMANDS[5]}"    \
                     2> >($logcmd)
-            ) || rc=$?
-        if [[ $rc -ne 0 ]]; then
-            exit $OK
-        fi
+            ) || exit $OK
         process_menu1_choice
     done
 }
@@ -323,8 +313,6 @@ function process_menu2 {
 
 # This function shows and processes menu #2 in GUI mode.
 function process_menu2_gui {
-    local -i rc=0
-
     while true; do
         title=$MENU2_TITLE
         REPLY=$(
@@ -348,10 +336,7 @@ function process_menu2_gui {
                     FALSE 6 "${MENU2_ACTIONS[6]}" "${MENU2_COMMANDS[6]}"    \
                     FALSE 7 "${MENU2_ACTIONS[7]}" "${MENU2_COMMANDS[7]}"    \
                     2> >($logcmd)
-            ) || rc=$?
-        if [[ $rc -ne 0 ]]; then
-            break
-        fi
+            ) || break
         process_menu2_choice
     done
 }
@@ -520,7 +505,7 @@ function execute_command {
         gui_option='--gui'
     fi
     "$PROGRAM_PATH/$cmd" "$arg" $gui_option -- || rc=$?
-    msg_log  "$command: rc=$rc"
+    msg_log "$command: rc=$rc"
     if $option_gui; then
         wait_for_enter
     fi
diff --git a/usr/bin/kz-setup b/usr/bin/kz-setup
--- a/usr/bin/kz-setup
+++ b/usr/bin/kz-setup
@@ -85,7 +85,6 @@ declare option_reset=false
 # This function handles the script options and arguments.
 function check_input {
     local -i app_arg_num=0
-    local -i rc=0
     local parsed=''
 
     parsed=$(
@@ -94,11 +93,7 @@ function check_input {
                 --longoptions   "$OPTIONS_LONG$X_OPTIONS_LONG"      \
                 --name          "$DISPLAY_NAME"                     \
                 --              "$@"
-        ) || rc=$?
-    if [[ $rc -ne $OK ]]; then
-        printf '%s\n' "$USAGE_LINE"
-        exit $ERROR
-    fi
+        ) || ( printf '%s\n' "$USAGE_LINE"; exit $ERROR )
     eval set -- "$parsed"
 
     process_common_options "$@"
@@ -437,7 +432,6 @@ function process_command_file {
 function execute_command {
     local cmd=${1:-unknown}
     local app_name_line=''
-    local -i rc=0
 
     commands_found=true
     ((++cmd_seq_num))
@@ -465,10 +459,7 @@ function execute_command {
 
     msg_log  "$app_name_line"
     msg_log  "${blue}$cmd${normal}"
-    eval "$cmd" |& $logcmd || rc=$?
-    if [[ $rc -gt $OK ]]; then
-        failed_apps[$app_name]=$app_name
-    fi
+    eval "$cmd" |& $logcmd || failed_apps[$app_name]=$app_name
 }
 
 
diff --git a/usr/bin/kz-wifi b/usr/bin/kz-wifi
--- a/usr/bin/kz-wifi
+++ b/usr/bin/kz-wifi
@@ -55,7 +55,6 @@ declare option_gui=false
 
 # This function handles the script options and arguments.
 function check_input {
-    local -i rc=0
     local parsed=''
 
     parsed=$(
@@ -64,11 +63,7 @@ function check_input {
                 --longoptions   "$OPTIONS_LONG$X_OPTIONS_LONG"      \
                 --name          "$DISPLAY_NAME"                     \
                 --              "$@"
-        ) || rc=$?
-    if [[ $rc -ne $OK ]]; then
-        printf '%s\n' "$USAGE_LINE"
-        exit $ERROR
-    fi
+        ) || ( printf '%s\n' "$USAGE_LINE"; exit $ERROR )
     eval set -- "$parsed"
 
     process_common_options "$@"
@@ -105,8 +100,8 @@ function check_input {
 
 # This function processes the script options and arguments.
 function process_input {
+    local -i nmcli_rc=''
     local nmcli_output=''
-    local -i rc=''
     local text
     text=$(gettext "Record this data to connect to the wireless network \
 later.")
@@ -124,8 +119,8 @@ $text"
     else
         msg_info "$(gettext 'WiFi data:')
 "
-        nmcli device wifi show-password 2> >($logcmd) || rc=$?
-        if [[ $rc -eq 0 ]]; then
+        nmcli device wifi show-password 2> >($logcmd) || nmcli_rc=$?
+        if [[ $nmcli_rc -eq 0 ]]; then
             msg_info "
 $text"
         else
