Introduce error log

diff --git a/usr/bin/kz-backup b/usr/bin/kz-backup
--- a/usr/bin/kz-backup
+++ b/usr/bin/kz-backup
@@ -54,10 +54,11 @@ readonly OPTIONS_LONG='gui,target:,help,manual,usage,version'
 # Globals
 ###############################################################################
 
+declare -i BACKUP_RC=0
+declare ERRORLOG=''
 declare OPTION_GUI=false
 declare TARGET_MEDIUM=''
 declare TARGET=''
-declare -i BACKUP_RC=0
 
 
 ###############################################################################
@@ -512,9 +513,10 @@ EOF
 
     title=$(gettext 'Backup home folder')
     text=$(gettext 'Preparing backup (this may take a while)')
+    kz.debugmsg "$title"...
+    ERRORLOG=$(mktemp -t "$PROGRAM_NAME-errorlog-XXXXXXXXXX")
 
     if $OPTION_GUI; then
-        kz.debugmsg "$title..."
         rsync   --archive                       \
                 --acls                          \
                 --xattrs                        \
@@ -524,7 +526,8 @@ EOF
                 --delete-excluded               \
                 "$HOME"/                        \
                 "$TARGET"/                      \
-                2> >($PROGRAM_LOGS)             |
+                1> >($PROGRAM_LOGS)             \
+                2>> "$ERRORLOG"                 |
         sed     --expression='s/^/#/'           |
         zenity  --progress                      \
                 --auto-close                    \
@@ -546,7 +549,7 @@ EOF
                 --exclude-from="$exclude_file"  \
                 --delete-excluded               \
                 "$HOME"/                        \
-                "$TARGET"/                      2> /dev/null || BACKUP_RC=$?
+                "$TARGET"/                      2>> "$ERRORLOG" || BACKUP_RC=$?
     fi
 
     text=$(gettext "Writing data from memory (this may take a while)")
@@ -560,11 +563,13 @@ EOF
                 --width     600         \
                 --height    50          \
                 --title     "$title"    \
-                --text      "$text"     &> >($PROGRAM_LOGS)
+                --text      "$text"     \
+                1> >($PROGRAM_LOGS)     \
+                2>> "$ERRORLOG"
     else
         text+='...'
         kz.infomsg "$text"
-        sync |& $PROGRAM_LOGS
+        sync 1> >($PROGRAM_LOGS) 2>> "$ERRORLOG"
     fi
 }
 
@@ -573,22 +578,46 @@ EOF
 function term() {
     local -i num_users=0
     local -i rc=0
+    local program_name=${PROGRAM_NAME/kz-/kz }
     local text=''
+    local title=''
     local users=''
 
     if [[ $BACKUP_RC -ne 0 ]]; then
+        title="$PROGRAM_DESC $(gettext 'error messages') ($program_name)"
+        # Errors also to the log.
+        kz.logmsg '==========================================================='
+        kz.logmsg "$title $ERRORLOG:"
+        printf '%s' "$(<"$ERRORLOG")" |& $PROGRAM_LOGS
+        kz.logmsg '==========================================================='
+
         text="$(eval_gettext "Backup ended with warnings or errors.
 
 Some files may not be readable, or
 were any files added or removed while creating the backup, or
 is there not enough space on \$TARGET.")
 
-$(eval_gettext "Use \"journalctl --boot --id=\$PROGRAM_NAME\" in the Terminal \
+$(gettext "Please check the error messages after this for more information, \
+or")
+$(eval_gettext "use \"journalctl --boot --id=\$PROGRAM_NAME\" in the Terminal \
 to view the log messages.")
 
 $(gettext "Try creating the back up again.")"
         kz.errmsg "$text"
+
+        if $OPTION_GUI; then
+            zenity  --text-info             \
+                    --filename="$ERRORLOG"  \
+                    --width     700         \
+                    --height    500         \
+                    --title     "$title"    2> /dev/null || true
+        else
+            kz.infomsg "$title $ERRORLOG:"
+            less --no-init --quit-if-one-screen "$ERRORLOG"
+        fi
         exit 1
+    else
+        rm "$ERRORLOG" |& $PROGRAM_LOGS
     fi
 
     users=$(
diff --git a/usr/bin/kz-install b/usr/bin/kz-install
--- a/usr/bin/kz-install
+++ b/usr/bin/kz-install
@@ -67,10 +67,11 @@ readonly COMMANDLINE_ARGS=("$@")
 # Globals
 ###############################################################################
 
+declare -A FAILED_APPS=()
+declare ERRORLOG=''
 declare OPTION_GUI=false
 declare OPTION_REMOVE=false
 declare REBOOT=true
-declare -A FAILED_APPS=()
 
 
 ###############################################################################
@@ -420,6 +421,7 @@ function install_apps() {
     title=$(gettext 'Install apps')
     text=$(gettext 'Prepare installation')
     kz.debugmsg "$title"...
+    ERRORLOG=$(mktemp -t "$PROGRAM_NAME-errorlog-XXXXXXXXXX")
 
     if $OPTION_GUI; then
         # With '|& zenity --progress' global variables from called functions
@@ -471,6 +473,8 @@ function process_command_file() {
                         "$app_seq_num"      \
                         "$app_tot_num"      \
                         "$app_name"
+                # To corrolate possible error messages with app name.
+                printf '%s\n' "-- App $app_name" >> "$ERRORLOG"
                 ;;
             '' | '#'* )
                 # Empty or comment line.
@@ -521,15 +525,20 @@ function execute_command() {
     if $OPTION_GUI; then
         # Use 'pkexec' to run the command in graphical mode.
         # This is required for commands that need root privileges.
-        pkexec /usr/bin/kz-install-cmd "$cmd"           \
-            &> >(systemd-cat --identifier=kz-install)   ||
-            FAILED_APPS[$app_name]=$app_name
+        pkexec  /usr/bin/kz-install-cmd \
+                "$cmd"                  \
+                1> >($PROGRAM_LOGS)     \
+                2>> "$ERRORLOG"         ||
+                FAILED_APPS[$app_name]=$app_name
     else
         # Use 'sudo' to run the command in terminal mode.
         # This script is started with 'sudo' so the command is run with root
         # privileges.
         # Use 'eval' to execute the command in the variable as a shell command.
-        eval "$cmd" &> >($PROGRAM_LOGS) || FAILED_APPS[$app_name]=$app_name
+        eval    "$cmd"              \
+                1> >($PROGRAM_LOGS) \
+                2>> "$ERRORLOG"     ||
+                FAILED_APPS[$app_name]=$app_name
     fi
 }
 
@@ -538,19 +547,43 @@ function execute_command() {
 function term() {
     local cmd='sudo systemctl reboot'
     local operation=''
+    local program_name=${PROGRAM_NAME/kz-/kz }
     local text=''
+    local title=''
 
     if [[ ${FAILED_APPS[*]} ]]; then
+        title="$PROGRAM_DESC $(gettext 'error messages') ($program_name)"
+        # Errors also to the log.
+        kz.logmsg '==========================================================='
+        kz.logmsg "$title $ERRORLOG:"
+        printf '%s' "$(<"$ERRORLOG")" |& $PROGRAM_LOGS
+        kz.logmsg '==========================================================='
+
         text="$(gettext "The installation of the following apps contains \
 errors:")
 ${FAILED_APPS[*]}
 
-$(eval_gettext "Use \"journalctl --boot --id=\$PROGRAM_NAME\" in the Terminal \
+$(gettext "Please check the error messages after this for more information, \
+or")
+$(eval_gettext "use \"journalctl --boot --id=\$PROGRAM_NAME\" in the Terminal \
 to view the log messages.")
 
 $(gettext "Try installing the apps again.")"
         kz.errmsg "$text"
+
+        if $OPTION_GUI; then
+            zenity  --text-info             \
+                    --filename="$ERRORLOG"  \
+                    --width     700         \
+                    --height    500         \
+                    --title     "$title"    2> /dev/null || true
+        else
+            kz.infomsg "$title $ERRORLOG:"
+            less --no-init --quit-if-one-screen "$ERRORLOG"
+        fi
         exit 1
+    else
+        rm "$ERRORLOG" |& $PROGRAM_LOGS
     fi
 
     operation=$(gettext 'install')
@@ -575,12 +608,12 @@ changing system settings.")"
             # This is required for commands that need root privileges.
             pkexec /usr/bin/kz-install-cmd "$cmd"
         else
+            kz.wait_for_enter
             # Use 'sudo' to run the command in terminal mode.
             # This script is started with 'sudo' so the command is run with
             # root privileges.
             # Use 'eval' to execute the command in the variable as a shell
             # command.
-            kz.wait_for_enter
             eval "$cmd"
         fi
     fi
diff --git a/usr/bin/kz-restore b/usr/bin/kz-restore
--- a/usr/bin/kz-restore
+++ b/usr/bin/kz-restore
@@ -54,9 +54,10 @@ readonly OPTIONS_LONG='gui,source:,help,manual,usage,version'
 # Globals
 ###############################################################################
 
+declare -i RESTORE_RC=0
+declare ERRORLOG=''
 declare OPTION_GUI=false
 declare SOURCE_MEDIUM=''
-declare -i RESTORE_RC=0
 
 
 ###############################################################################
@@ -247,16 +248,18 @@ function restore_backup() {
 
     title=$(gettext 'Restore home folder')
     text=$(gettext 'Preparing restore (this can take a while)')
+    kz.debugmsg "$title"...
+    ERRORLOG=$(mktemp -t "$PROGRAM_NAME-errorlog-XXXXXXXXXX")
 
     if $OPTION_GUI; then
-        kz.debugmsg "$title"...
         rsync   --archive               \
                 --acls                  \
                 --xattrs                \
                 --verbose               \
                 "$source"/              \
                 "$HOME"/                \
-                2> >($PROGRAM_LOGS)     |
+                1> >($PROGRAM_LOGS)     \
+                2>> "$ERRORLOG"         |
         sed     --expression='s/^/#/'   |
         zenity  --progress              \
                 --auto-close            \
@@ -275,7 +278,7 @@ function restore_backup() {
                 --verbose               \
                 --human-readable        \
                 "$source"/              \
-                "$HOME"/                2> /dev/null || RESTORE_RC=$?
+                "$HOME"/                2>> "$ERRORLOG" || RESTORE_RC=$?
     fi
 }
 
@@ -310,22 +313,45 @@ function restore_setting_desktop() {
 function term() {
     local -i num_users=0
     local -i rc=0
+    local program_name=${PROGRAM_NAME/kz-/kz }
     local text=''
     local users=''
 
     if [[ $RESTORE_RC -ne 0 ]]; then
+        title="$PROGRAM_DESC $(gettext 'error messages') ($program_name)"
+        # Errors also to the log.
+        kz.logmsg '==========================================================='
+        kz.logmsg "$title $ERRORLOG:"
+        printf "%s" "$(<"$ERRORLOG")" |& $PROGRAM_LOGS
+        kz.logmsg '==========================================================='
+
         text="$(eval_gettext "Restore ended with warnings or errors.
 
 Some files may not be readable, or
 were any files added or removed while restoring the backup, or
 is there not enough space on \$HOME.")
 
-$(eval_gettext "Use \"journalctl --boot --id=\$PROGRAM_NAME\" in the Terminal \
+$(gettext "Please check the error messages after this for more information, \
+or")
+$(eval_gettext "use \"journalctl --boot --id=\$PROGRAM_NAME\" in the Terminal \
 to view the log messages.")
 
 $(gettext "Try restoring the back up again.")"
         kz.errmsg "$text"
+
+        if $OPTION_GUI; then
+            zenity  --text-info             \
+                    --filename="$ERRORLOG"  \
+                    --width     700         \
+                    --height    500         \
+                    --title     "$title"    2> /dev/null || true
+        else
+            kz.infomsg "$title $ERRORLOG:"
+            less --no-init --quit-if-one-screen "$ERRORLOG"
+        fi
         exit 1
+    else
+        rm "$ERRORLOG" |& $PROGRAM_LOGS
     fi
 
     num_users=$(find /home/* -prune -print | wc --lines)
diff --git a/usr/bin/kz-setup b/usr/bin/kz-setup
--- a/usr/bin/kz-setup
+++ b/usr/bin/kz-setup
@@ -67,10 +67,11 @@ readonly on='on'
 # Globals
 ###############################################################################
 
+declare -A FAILED_APPS=()
+declare ERRORLOG=''
+declare LOGOUT=true
 declare OPTION_GUI=false
 declare OPTION_RESET=false
-declare LOGOUT=true
-declare -A FAILED_APPS=()
 
 
 ###############################################################################
@@ -413,6 +414,7 @@ function setup_apps() {
     title=$(gettext 'Set up apps')
     text=$(gettext 'Preparing set up')
     kz.debugmsg "$title"...
+    ERRORLOG=$(mktemp -t "$PROGRAM_NAME-errorlog-XXXXXXXXXX")
 
     if $OPTION_GUI; then
         # With '|& zenity --progress' global variables from called functions
@@ -464,6 +466,8 @@ function process_command_file() {
                         "$app_seq_num"      \
                         "$app_tot_num"      \
                         "$app_name"
+                # To corrolate possible error messages with app name.
+                printf '%s\n' "-- App $app_name" >> "$ERRORLOG"
                 ;;
             '' | '#'* )
                 # Empty or comment line.
@@ -511,25 +515,53 @@ function execute_command() {
     fi
 
     kz.debugmsg "$cmd"
-    eval "$cmd" &> >($PROGRAM_LOGS) || FAILED_APPS[$app_name]=$app_name
+    # Use 'eval' to execute the command in the variable as a shell command.
+    eval    "$cmd"              \
+            1> >($PROGRAM_LOGS) \
+            2>> "$ERRORLOG"     ||
+            FAILED_APPS[$app_name]=$app_name
 }
 
 
 # This function controls the termination of the script.
 function term() {
     local operation=''
+    local program_name=${PROGRAM_NAME/kz-/kz }
     local text=''
+    local title=''
 
     if [[ ${FAILED_APPS[*]} ]]; then
+        title="$PROGRAM_DESC $(gettext 'error messages') ($program_name)"
+        # Errors also to the log.
+        kz.logmsg '==========================================================='
+        kz.logmsg "$title $ERRORLOG:"
+        printf "%s" "$(<"$ERRORLOG")" |& $PROGRAM_LOGS
+        kz.logmsg '==========================================================='
+
         text="$(gettext "The set up of the following apps contains errors:")
 ${FAILED_APPS[*]}
 
-$(eval_gettext "Use \"journalctl --boot --id=\$PROGRAM_NAME\" in the Terminal \
+$(gettext "Please check the error messages after this for more information, \
+or")
+$(eval_gettext "use \"journalctl --boot --id=\$PROGRAM_NAME\" in the Terminal \
 to view the log messages.")
 
 $(gettext "Try to set up the apps again.")"
         kz.errmsg "$text"
+
+        if $OPTION_GUI; then
+            zenity  --text-info             \
+                    --filename="$ERRORLOG"  \
+                    --width     700         \
+                    --height    500         \
+                    --title     "$title"    2> /dev/null || true
+        else
+            kz.infomsg "$title $ERRORLOG:"
+            less --no-init --quit-if-one-screen "$ERRORLOG"
+        fi
         exit 1
+    else
+        rm "$ERRORLOG" |& $PROGRAM_LOGS
     fi
 
     operation=$(gettext 'set up')
