feat: improve cleanup process and simplify temporary file naming in kz-get

diff --git a/usr/bin/kz-get b/usr/bin/kz-get
--- a/usr/bin/kz-get
+++ b/usr/bin/kz-get
@@ -68,8 +68,8 @@ function process() {
         # Trap exit signal to clean up only getkz files if in debug mode.
         trap 'rm --force getkz getkz.{1..99}' EXIT
     else
-        # Clean up temporary files if not in debug mode.
-        trap 'rm --force getkz getkz.{1..99} /tmp/kz-get-*' EXIT
+        # Clean up temporary and getkz files if not in debug mode.
+        trap 'rm --force getkz getkz.{1..99} /tmp/kz-*.deb' EXIT
     fi
 
     become_check || exit 0
@@ -179,10 +179,10 @@ function install_deb_package() {
 
     if $OPTION_DEV; then
         kz_deb_site_file=$packages_url/kz-dev_4.2.1-1_all.deb
-        kz_deb_local_file=$(mktemp -t "$PROGRAM_NAME-dev-XXXXXXXXXX.deb")
+        kz_deb_local_file=$(mktemp -t "kz-dev-XXXXXXXXXX.deb")
     else
         kz_deb_site_file=$packages_url/kz_4.2.1-1_all.deb
-        kz_deb_local_file=$(mktemp -t "$PROGRAM_NAME-XXXXXXXXXX.deb")
+        kz_deb_local_file=$(mktemp -t "kz-XXXXXXXXXX.deb")
     fi
 
     if type kz &> /dev/null; then
