Add additional [fail] and [hint] message

diff --git a/usr/bin/kz-get b/usr/bin/kz-get
--- a/usr/bin/kz-get
+++ b/usr/bin/kz-get
@@ -18,8 +18,17 @@ declare KZ_COMMON_LOCAL_FILE
         KZ_COMMON_LOCAL_FILE=$(mktemp -t "kz-get-XXXXXXXXXX.sh")
 wget    --output-document="$KZ_COMMON_LOCAL_FILE" $KZ_COMMON_SITE_FILE |&
         systemd-cat --identifier=kz-get --priority=debug
-source  "$KZ_COMMON_LOCAL_FILE" 2> >(
-        systemd-cat --identifier=kz-get --priority=debug)
+if      [[ ${PIPESTATUS[0]} -gt 0 ]]; then   
+        echo '[fail] download kz_common.sh' >&2
+        echo '[hint] journalctl --no-pager --pager-end --identifier=kz-get'
+        exit 1
+fi
+if  !   source "$KZ_COMMON_LOCAL_FILE" 2> >(
+        systemd-cat --identifier=kz-get --priority=debug); then
+        echo '[fail] source kz_common.sh' >&2
+        echo '[hint] journalctl --no-pager --pager-end --identifier=kz-get'
+        exit 1
+fi
 rm      --verbose "$KZ_COMMON_LOCAL_FILE" |&
         systemd-cat --identifier=kz-get --priority=debug
 
