Refresh package metadata

diff --git a/usr/bin/kz-get b/usr/bin/kz-get
--- a/usr/bin/kz-get
+++ b/usr/bin/kz-get
@@ -126,6 +126,14 @@ function prepare_processing() {
         printf '\b%s' '=>'
         sleep 1
     done &
+
+    # Refresh package metadata.
+    if $DEB; then
+        sudo apt-get update |& $LOGCMD || true
+    elif $RPM; then
+        # Exit code 100 means there are updates available ==> ' || true'.
+        sudo dnf check-update --refresh |& $LOGCMD || true
+    fi
 }
 
 
