Check existence with type

diff --git a/usr/bin/kz-getdeb b/usr/bin/kz-getdeb
--- a/usr/bin/kz-getdeb
+++ b/usr/bin/kz-getdeb
@@ -18,10 +18,12 @@ PROGRAM_PATH=$(cd "$(dirname "$(realpath "$0")")" && pwd)
 readonly PROGRAM_PATH
 source "$PROGRAM_PATH"/kz_common.sh 2> >(systemd-cat --identifier=kz-getdeb)
 
-# If source kz_common.sh has failed, e.g. in wget kz and bash kz sequence.
-export TEXTDOMAIN=kz
-export TEXTDOMAINDIR=/usr/share/locale
-source /usr/bin/gettext.sh
+if ! type gettext; then
+    # If source kz_common.sh has failed, e.g. in wget kz and bash kz sequence.
+    export TEXTDOMAIN=kz
+    export TEXTDOMAINDIR=/usr/share/locale
+    source /usr/bin/gettext.sh
+fi
 
 
 ###############################################################################
