Fix: standardize error log formatting across multiple scripts for consistency

diff --git a/usr/bin/kz-install b/usr/bin/kz-install
--- a/usr/bin/kz-install
+++ b/usr/bin/kz-install
@@ -702,7 +702,7 @@ install_apps() {
 
     ERROR_LOG=$(mktemp -t "$PROGRAM_NAME-error-XXXXXXXXXX.log")
     chmod --verbose 775 "$ERROR_LOG" |& $PROGRAM_LOGS
-    text="ERRORLOG $ERROR_LOG (stderr)"
+    text="ERRORLOG (stderr) $ERROR_LOG"
     printf '%s\n' "$text" > "$ERROR_LOG"
 
     title=$(gettext 'Install apps')
@@ -731,10 +731,10 @@ install_apps() {
 # This function reads commands from the command file for further processing.
 process_command_file() {
     local -i app_seq_num=0
-    local app_name_line=''
+    local app_desc=''
+    local app_line=''
     local app_name=''
     local command_record=''
-    local text=''
 
     text="$(gettext "Authentication is required to install apps and change \
 system settings")
@@ -758,6 +758,7 @@ $(gettext '         COMMAND...')"
                 ;;
             '#'*"$INSTALL"*'|'*'|'* )
                 # App record.
+                app_seq_num=$((app_seq_num + 1))
                 app_name=$(
                     printf  '%s\n'                  \
                             "$command_record"       |
@@ -765,17 +766,25 @@ $(gettext '         COMMAND...')"
                     cut     --delimiter=' '         \
                             --fields=3
                     )
-                app_seq_num=$((app_seq_num + 1))
-                printf  -v app_name_line    \
-                        "%3d/%-3d  %s"      \
-                        "$app_seq_num"      \
-                        "$app_tot_num"      \
-                        "$app_name"
+                app_desc=$(
+                    printf  '%s\n'                  \
+                            "$command_record"       |
+                    tr      --squeeze-repeats ' '   |
+                    cut     --delimiter='|'         \
+                            --fields=3
+                    )
+                printf  -v app_line            \
+                        "%3d/%-3d  %s |%s"          \
+                        "$app_seq_num"              \
+                        "$app_tot_num"              \
+                        "$app_name"                 \
+                        "$app_desc"
                 if [[ $UI_MODE = 'cli' ]]; then
-                    printf '%s\n' "$app_name_line"
+                    printf '%s\n' "$app_line"
                 fi
-                # To corrolate possible error messages with app name.
-                printf '%s\n' "== App $app_name" >> "$ERROR_LOG"
+                # To corrolate possible error messages with app name and 
+                # description.
+                printf 'APP %s |%s\n' "$app_name" "$app_desc" >> "$ERROR_LOG"
                 ;;
             '#'* )
                 # Skip comment record.
@@ -798,10 +807,10 @@ execute_command() {
     local cmd_dis=''
     local -i pkexec_rc=0
 
-    kz.logmsg "$app_name_line\n\n         $cmd"
+    kz.logmsg "$app_line\n\n         $cmd"
 
     if [[ $UI_MODE = 'gui' ]]; then
-        printf '%s\n' "#$app_name_line\n\n$cmd"
+        printf '%s\n' "#$app_line\n\n$cmd"
         check_debian_package_manager
         pkexec  /usr/bin/kz-install-pkexec  \
                 "${XDG_CURRENT_DESKTOP-}"   \
@@ -839,11 +848,11 @@ execute_command() {
         done
         # This tput locks the cursor position top-left to prevent flickering.
         tput cup 0 0
-        dialog  --mouse                                         \
-                --backtitle "$PROGRAM_NAME"                     \
-                --title     "$title"                            \
-                --infobox   "$app_name_line\n\n         $cmd"   \
-                10 90                                           || true
+        dialog  --mouse                                     \
+                --backtitle "$PROGRAM_NAME"                 \
+                --title     "$title"                        \
+                --infobox   "$app_line\n\n         $cmd"    \
+                10 90                                       || true
         check_debian_package_manager
         eval    "$cmd"              \
                 1> >($PROGRAM_LOGS) \
@@ -895,8 +904,7 @@ term() {
     local title=''
 
     # Error log also to the standard log.
-    text="\
-ERRORLOG $ERROR_LOG (stderr)"
+    text="ERRORLOG (stderr) $ERROR_LOG"
     printf '%s\n' "$text" >> "$ERROR_LOG"
     printf '%s' "$(<"$ERROR_LOG")" |& $PROGRAM_LOGS
 
@@ -904,7 +912,7 @@ ERRORLOG $ERROR_LOG (stderr)"
         title="$PROGRAM_DESC $(gettext 'error messages')"
         text="$(gettext "The installation of the following apps contains \
 errors:")
-${FAILED_APPS[*]}
+ ${FAILED_APPS[*]}
 
 $(gettext 'Actions to take:')
 $(gettext 'Check the error messages after this.')
@@ -933,7 +941,7 @@ $(gettext 'Check the error messages after this.')
         else
             prompt=$(gettext 'Press the Enter key to continue [Enter]: ')
             read -rp "$prompt" < /dev/tty
-            kz.infomsg "$title $ERROR_LOG:"
+            kz.infomsg "$title:"
             less --no-init --quit-if-one-screen "$ERROR_LOG"
         fi
         exit 1
diff --git a/usr/bin/kz-setup b/usr/bin/kz-setup
--- a/usr/bin/kz-setup
+++ b/usr/bin/kz-setup
@@ -667,7 +667,7 @@ setup_apps() {
     fi
 
     ERROR_LOG=$(mktemp -t "$PROGRAM_NAME-error-XXXXXXXXXX.log")
-    text="ERRORLOG $ERROR_LOG (stderr)"
+    text="ERRORLOG (stderr) $ERROR_LOG"
     printf '%s\n' "$text" > "$ERROR_LOG"
 
     title=$(gettext 'Set up apps')
@@ -696,7 +696,8 @@ setup_apps() {
 # This function reads commands from the command file for further processing.
 process_command_file() {
     local -i app_seq_num=0
-    local app_name_line=''
+    local app_desc=''
+    local app_line=''
     local app_name=''
     local command_record=''
 
@@ -714,6 +715,7 @@ $(gettext '         COMMAND...')"
                 ;;
             '#'*"$SETUP"*'|'*'|'* )
                 # App record.
+                app_seq_num=$((app_seq_num + 1))
                 app_name=$(
                     printf  '%s\n'                  \
                             "$command_record"       |
@@ -721,17 +723,25 @@ $(gettext '         COMMAND...')"
                     cut     --delimiter=' '         \
                             --fields=3
                     )
-                app_seq_num=$((app_seq_num + 1))
-                printf  -v app_name_line    \
-                        "%3d/%-3d  %s"      \
-                        "$app_seq_num"      \
-                        "$app_tot_num"      \
-                        "$app_name"
+                app_desc=$(
+                    printf  '%s\n'                  \
+                            "$command_record"       |
+                    tr      --squeeze-repeats ' '   |
+                    cut     --delimiter='|'         \
+                            --fields=3
+                    )
+                printf  -v app_line                 \
+                        "%3d/%-3d  %s |%s"          \
+                        "$app_seq_num"              \
+                        "$app_tot_num"              \
+                        "$app_name"                 \
+                        "$app_desc"
                 if [[ $UI_MODE = 'cli' ]]; then
-                    printf '%s\n' "$app_name_line"
+                    printf '%s\n' "$app_line"
                 fi
-                # To corrolate possible error messages with app name.
-                printf '%s\n' "== App $app_name" >> "$ERROR_LOG"
+                # To corrolate possible error messages with app name and 
+                # description.
+                printf 'APP %s |%s\n' "$app_name" "$app_desc" >> "$ERROR_LOG"
                 ;;
             '#'* )
                 # Skip comment record.
@@ -753,18 +763,18 @@ execute_command() {
     local -i cmd_dis_max=0
     local cmd_dis=''
 
-    kz.logmsg "$app_name_line\n\n         $cmd"
+    kz.logmsg "$app_line\n\n         $cmd"
 
     if [[ $UI_MODE = 'gui' ]]; then
-        printf '%s\n' "#$app_name_line\n\n$cmd"
+        printf '%s\n' "#$app_line\n\n$cmd"
     elif [[ $UI_MODE = 'tui' ]]; then
         # This tput locks the cursor position top-left to prevent flickering.
         tput cup 0 0
-        dialog  --mouse                                         \
-                --backtitle "$PROGRAM_NAME"                     \
-                --title     "$title"                            \
-                --infobox   "$app_name_line\n\n         $cmd"   \
-                10 90                                           || true
+        dialog  --mouse                                     \
+                --backtitle "$PROGRAM_NAME"                 \
+                --title     "$title"                        \
+                --infobox   "$app_line\n\n         $cmd"    \
+                10 90                                       || true
     else
         # Ellipsize terminal output.
         # Width 9 characters less, 9 for leading spaces.
@@ -794,8 +804,7 @@ term() {
     local title=''
 
     # Error log also to the main log.
-    text="\
-ERRORLOG $ERROR_LOG (stderr)"
+    text="ERRORLOG (stderr) $ERROR_LOG"
     printf '%s\n' "$text" >> "$ERROR_LOG"
     printf '%s' "$(<"$ERROR_LOG")" |& $PROGRAM_LOGS
 
@@ -831,7 +840,7 @@ $(gettext 'Check the error messages after this.')
         else
             prompt=$(gettext 'Press the Enter key to continue [Enter]: ')
             read -rp "$prompt" < /dev/tty
-            kz.infomsg "$title $ERROR_LOG:"
+            kz.infomsg "$title:"
             less --no-init --quit-if-one-screen "$ERROR_LOG"
         fi
         exit 1
